package mx.model;
// Generated 27/04/2019 10:13:54 PM by Hibernate Tools 4.3.1



/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private int id;
     private String avisoCorreo;

    public Mensaje() {
    }

	
    public Mensaje(int id) {
        this.id = id;
    }
    public Mensaje(int id, String avisoCorreo) {
       this.id = id;
       this.avisoCorreo = avisoCorreo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getAvisoCorreo() {
        return this.avisoCorreo;
    }
    
    public void setAvisoCorreo(String avisoCorreo) {
        this.avisoCorreo = avisoCorreo;
    }




}


