package mx.model;
// Generated 27/04/2019 10:13:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Queja generated by hbm2java
 */
public class Queja  implements java.io.Serializable {


     private int id;
     private String rfc;
     private String comentarioprov;
     private Date feccomentario;
     private String comentario;
     private Date feccomenresp;

    public Queja() {
    }

	
    public Queja(int id) {
        this.id = id;
    }
    public Queja(int id, String rfc, String comentarioprov, Date feccomentario, String comentario, Date feccomenresp) {
       this.id = id;
       this.rfc = rfc;
       this.comentarioprov = comentarioprov;
       this.feccomentario = feccomentario;
       this.comentario = comentario;
       this.feccomenresp = feccomenresp;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getComentarioprov() {
        return this.comentarioprov;
    }
    
    public void setComentarioprov(String comentarioprov) {
        this.comentarioprov = comentarioprov;
    }
    public Date getFeccomentario() {
        return this.feccomentario;
    }
    
    public void setFeccomentario(Date feccomentario) {
        this.feccomentario = feccomentario;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Date getFeccomenresp() {
        return this.feccomenresp;
    }
    
    public void setFeccomenresp(Date feccomenresp) {
        this.feccomenresp = feccomenresp;
    }




}


