package mx.model;
// Generated 27/04/2019 10:13:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String correo;
     private String codperfil;
     private String rfc;
     private String clave;
     private String telefono;
     private String activacion;
     private Date fecalta;
     private String enviarpass;
     private String enviaraviso;
     private String codactivacion;
     private String responsable;

    public Usuario() {
    }

	
    public Usuario(int id) {
        this.id = id;
    }
    public Usuario(int id, String correo, String codperfil, String rfc, String clave, String telefono, String activacion, Date fecalta, String enviarpass, String enviaraviso, String codactivacion, String responsable) {
       this.id = id;
       this.correo = correo;
       this.codperfil = codperfil;
       this.rfc = rfc;
       this.clave = clave;
       this.telefono = telefono;
       this.activacion = activacion;
       this.fecalta = fecalta;
       this.enviarpass = enviarpass;
       this.enviaraviso = enviaraviso;
       this.codactivacion = codactivacion;
       this.responsable = responsable;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getCodperfil() {
        return this.codperfil;
    }
    
    public void setCodperfil(String codperfil) {
        this.codperfil = codperfil;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getActivacion() {
        return this.activacion;
    }
    
    public void setActivacion(String activacion) {
        this.activacion = activacion;
    }
    public Date getFecalta() {
        return this.fecalta;
    }
    
    public void setFecalta(Date fecalta) {
        this.fecalta = fecalta;
    }
    public String getEnviarpass() {
        return this.enviarpass;
    }
    
    public void setEnviarpass(String enviarpass) {
        this.enviarpass = enviarpass;
    }
    public String getEnviaraviso() {
        return this.enviaraviso;
    }
    
    public void setEnviaraviso(String enviaraviso) {
        this.enviaraviso = enviaraviso;
    }
    public String getCodactivacion() {
        return this.codactivacion;
    }
    
    public void setCodactivacion(String codactivacion) {
        this.codactivacion = codactivacion;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }




}


